// <auto-generated />
using System;
using EfCoreNestedOwnedEntitiesProblem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreNestedOwnedEntitiesProblem.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCoreNestedOwnedEntitiesProblem.EntityOne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EntityOnes");
                });

            modelBuilder.Entity("EfCoreNestedOwnedEntitiesProblem.EntityTwo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EntityTwos");
                });

            modelBuilder.Entity("EfCoreNestedOwnedEntitiesProblem.EntityOne", b =>
                {
                    b.OwnsOne("EfCoreNestedOwnedEntitiesProblem.LvlOne", "MyProp", b1 =>
                        {
                            b1.Property<Guid>("EntityOneId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("EntityOneId");

                            b1.ToTable("EntityOnes");

                            b1.WithOwner()
                                .HasForeignKey("EntityOneId");

                            b1.OwnsOne("EfCoreNestedOwnedEntitiesProblem.LvlTwo", "LvlTwo", b2 =>
                                {
                                    b2.Property<Guid>("LvlOneEntityOneId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("LvlOneEntityOneId");

                                    b2.ToTable("EntityOnes");

                                    b2.WithOwner()
                                        .HasForeignKey("LvlOneEntityOneId");

                                    b2.OwnsOne("EfCoreNestedOwnedEntitiesProblem.LvlThree", "LvlThree", b3 =>
                                        {
                                            b3.Property<Guid>("LvlTwoLvlOneEntityOneId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("MyInteger")
                                                .HasColumnType("int");

                                            b3.HasKey("LvlTwoLvlOneEntityOneId");

                                            b3.ToTable("EntityOnes");

                                            b3.WithOwner()
                                                .HasForeignKey("LvlTwoLvlOneEntityOneId");
                                        });

                                    b2.Navigation("LvlThree");
                                });

                            b1.Navigation("LvlTwo");
                        });

                    b.Navigation("MyProp");
                });

            modelBuilder.Entity("EfCoreNestedOwnedEntitiesProblem.EntityTwo", b =>
                {
                    b.OwnsOne("EfCoreNestedOwnedEntitiesProblem.LvlOne", "MyOtherProp", b1 =>
                        {
                            b1.Property<Guid>("EntityTwoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("EntityTwoId");

                            b1.ToTable("EntityTwos");

                            b1.WithOwner()
                                .HasForeignKey("EntityTwoId");

                            b1.OwnsOne("EfCoreNestedOwnedEntitiesProblem.LvlTwo", "LvlTwo", b2 =>
                                {
                                    b2.Property<Guid>("LvlOneEntityTwoId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("LvlOneEntityTwoId");

                                    b2.ToTable("EntityTwos");

                                    b2.WithOwner()
                                        .HasForeignKey("LvlOneEntityTwoId");

                                    b2.OwnsOne("EfCoreNestedOwnedEntitiesProblem.LvlThree", "LvlThree", b3 =>
                                        {
                                            b3.Property<Guid>("LvlTwoLvlOneEntityTwoId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("MyInteger")
                                                .HasColumnType("int");

                                            b3.HasKey("LvlTwoLvlOneEntityTwoId");

                                            b3.ToTable("EntityTwos");

                                            b3.WithOwner()
                                                .HasForeignKey("LvlTwoLvlOneEntityTwoId");
                                        });

                                    b2.Navigation("LvlThree");
                                });

                            b1.Navigation("LvlTwo");
                        });

                    b.Navigation("MyOtherProp");
                });
#pragma warning restore 612, 618
        }
    }
}
